openapi: 3.0.4
info:
  title: Bulk Logistics API
  version: 1.0.0
  description: |
    The Bulk Logistics API enables the transfer of goods and machinery between suppliers and phone manufacturing companies within the simulated cellphone supply chain economy.

    Bulk Logistics plays a critical role in ensuring the continuous flow of manufactured components—such as electronics screens, and cases from suppliers to phone companies (e.g Pear and SumSang). It may also handle delivery of equipment sourced from The Hand of Hḗphaistos, and Recycler to companies within the supply chain.

    Key responsibilities include:
    - Managing shipment orders between entities
    - Tracking goods in transit
    - Supporting logistics analytics and capacity planning
    - Coordinating with manufacturing schedules and raw material supply
    description: Production server

servers:
  - url: http://{environment}/api/v1
    description: Local development server
    environment:
      default: localhost:3000
      enum:
        - localhost:5000
        - localhost:8000
      description: Localhost environment for development
  - url: https://api.bulk-logistics.example.com/v1 # To be replaced with the actual url

tags:
  - name: Pickup Requests
    description: |
      Manage requests to pick up and transfer goods from one company to another.

  - name: Pickup Request Items
    description: |
      Represents the items included in a pickup request.

  - name: Shipments
    description: |
      Handle shipment dispatch, tracking, and status management.

  - name: Shipment Items
    description: |
      Track and manage the items associated with a shipment.

  - name: Vehicles
    description: |
      Manage logistics vehicles and their types.

  - name: Companies
    description: |
      Information related to companies participating in the logistics process.

  - name: Item Definitions
    description: |
      Define the items that can be transported and their associated capacity types.

  - name: Capacity Types
    description: |
      Represent types of capacity units used to measure item and vehicle capacity.

  - name: Transaction Categories
    description: |
      Categorize financial transactions related to logistics operations.

  - name: Transaction Ledger
    description: |
      Track financial transactions related to pickups, shipments, and logistics costs.

  - name: Transaction Statuses
    description: |
      Manage status values for financial transactions.

  - name: Shipment Statuses
    description: |
      Define and manage the lifecycle states of shipments.

paths:
  /pickup-requests:
    post:
      tags:
        - Pickup Requests
      summary: Create a new pickup request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PickupRequest"
      responses:
        201:
          description: Pickup request created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PickupRequestResponse"
    get:
      tags:
        - Pickup Requests
      summary: List all pickup requests
      responses:
        200:
          description: A list of pickup requests
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PickupRequestResponse"

  /pickup-requests/{id}:
    get:
      tags:
        - Pickup Requests
      summary: Get details of a specific pickup request
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Pickup request found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PickupRequestResponse"
        404:
          description: Pickup request not found
    put:
      tags:
        - Pickup Requests
      summary: Update a pickup request
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PickupRequest"
      responses:
        200:
          description: Pickup request updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PickupRequestResponse"
        404:
          description: Pickup request not found

  /pickup-requests/{id}/items:
    get:
      tags:
        - Pickup Request Items
      summary: List items in a pickup request
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: List of items in the pickup request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PickupRequestItemResponse"

  /shipments:
    get:
      tags:
        - Shipments
      summary: List all shipments
      responses:
        200:
          description: A list of shipments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ShipmentResponse"

  /shipments/{id}:
    get:
      tags:
        - Shipments
      summary: Get details of a specific shipment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Shipment found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ShipmentResponse"
        404:
          description: Shipment not found

components:
  schemas:
    # Shipment Status Schemas
    ShipmentStatusRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          maxLength: 50
          example: "Delivered"
    ShipmentStatusResponse:
      type: object
      properties:
        shipmentStatusId:
          type: integer
          readOnly: true
          example: 1
        name:
          type: string
          example: "Collected"

    # Shipment Schemas
    ShipmentRequest:
      type: object
      properties:
        dispatchDate:
          type: string
          format: date
          example: "2025-06-29"
        vehicleId:
          type: integer
          example: 1
        shipmentStatusId:
          type: integer
          example: 1
      required:
        - dispatchDate
        - vehicleId
        - shipmentStatusId
    ShipmentResponse:
      type: object
      properties:
        shipmentId:
          type: integer
          readOnly: true
          example: 1
        dispatchDate:
          type: string
          format: date
          example: "2025-06-29"
        vehicle:
          $ref: "#/components/schemas/VehicleResponse"
        shipmentStatus:
          $ref: "#/components/schemas/ShipmentStatusResponse"

    # Shipment Item Detail Schemas
    ShipmentItemDetailRequest: # Do we need this?
      type: object
      properties:
        shipmentId:
          type: integer
          example: 1
        pickupRequestItemId:
          type: integer
          example: 1
        quantityTransported: # I don't think we need this since we can get this from the pickup request item
          type: integer
          example: 50
      required:
        - shipmentId
        - pickupRequestItemId
        - quantityTransported
    ShipmentItemDetailResponse:
      type: object
      properties:
        shipmentItemDetailId:
          type: integer
          readOnly: true
          example: 1
        shipmentId:
          type: integer
          example: 1
        pickupRequestItemId:
          type: integer
          example: 1
        quantityTransported:
          type: integer
          example: 50

    # Company Schemas
    CompanyRequest:
      type: object
      properties:
        companyName:
          type: string
          maxLength: 150
          example: "Case Supplier"
        certificateIdentifier:
          type: string
          maxLength: 255
          example: "cert-af32-98b-fe21"
        bankAccountNumber: # Not sure if we need it. Maybe for refund, should the request gets cancelled?
          type: string
          maxLength: 50
          nullable: true
          example: "9876543210"
      required:
        - companyName
        - certificateIdentifier
    CompanyResponse:
      type: object
      properties:
        companyId:
          type: integer
          readOnly: true
          example: 1
        companyName:
          type: string
          example: "Screen Supplier"
        certificateIdentifier:
          type: string
          example: "cert-af32-98b-fe21"
        bankAccountNumber:
          type: string
          nullable: true
          example: "9876543210"

    # Item Definition Schemas
    ItemDefinitionRequest:
      type: object
      properties:
        itemName:
          type: string
          maxLength: 100
          example: "Sand"
        capacityTypeId:
          type: integer
          example: 1
      required:
        - itemName
        - capacityTypeId
    ItemDefinitionResponse:
      type: object
      properties:
        itemDefinitionId:
          type: integer
          readOnly: true
          example: 1
        itemName:
          type: string
          example: "Sand"
        capacityType:
          $ref: "#/components/schemas/CapacityTypeResponse"

    # Capacity Type Schemas
    CapacityTypeRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 50
          example: "Kilograms"
      required:
        - name
    CapacityTypeResponse:
      type: object
      properties:
        capacityTypeId:
          type: integer
          readOnly: true
          example: 1
        name:
          type: string
          example: "Kilograms"

    # Vehicle Type Schemas
    VehicleTypeRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 50
          example: "Large Truck"
        dailyOperationalCost:
          type: number
          format: double
          example: 2500.75
        capacityTypeId:
          type: integer
          example: 1
        maximumCapacity:
          type: integer
          example: 5000
        maxPickupsPerDay:
          type: integer
          example: 10
        maxDropoffsPerDay:
          type: integer
          example: 10
      required:
        - name
        - dailyOperationalCost
        - capacityTypeId
        - maximumCapacity
        - maxPickupsPerDay
        - maxDropoffsPerDay
    VehicleTypeResponse:
      type: object
      properties:
        vehicleTypeId:
          type: integer
          readOnly: true
          example: 1
        name:
          type: string
          example: "Small Truck"
        dailyOperationalCost:
          type: number
          format: double
          example: 2500.75
        capacityTypeId:
          type: integer
          example: 1
        maximumCapacity:
          type: integer
          example: 5000
        maxPickupsPerDay:
          type: integer
          example: 10
        maxDropoffsPerDay:
          type: integer
          example: 10

    # Vehicle Schemas
    VehicleRequest:
      type: object
      properties:
        isActive:
          type: boolean
          example: true
        vehicleTypeId:
          type: integer
          example: 1
        purchaseDate:
          type: string
          format: date
          example: "2024-01-15"
      required:
        - isActive
        - vehicleTypeId
        - purchaseDate
    VehicleResponse:
      type: object
      properties:
        vehicleId:
          type: integer
          readOnly: true
          example: 1
        isActive:
          type: boolean
          example: true
        vehicleType:
          $ref: "#/components/schemas/VehicleTypeResponse"
        purchaseDate:
          type: string
          format: date
          example: "2024-01-15"

    # Pickup Request Schemas
    PickupRequest:
      type: object
      properties:
        requestingCompanyId:
          type: integer
          example: 1
        originCompanyId:
          type: integer
          example: 2
        destinationCompanyId:
          type: integer
          example: 3
        originalExternalOrderId:
          type: string
          maxLength: 255
          example: "ORD-998877"
        requestDate:
          type: string
          format: date
          example: "2025-06-28"
        completionDate:
          type: string
          format: date
          nullable: true
          example: "2025-06-30"
      required:
        - requestingCompanyId
        - originCompanyId
        - destinationCompanyId
        - originalExternalOrderId
        - requestDate

    PickupRequestResponse:
      type: object
      properties:
        pickupRequestId:
          type: integer
          readOnly: true
          example: 1
        requestingCompany:
          $ref: "#/components/schemas/CompanyResponse"
        originCompany:
          $ref: "#/components/schemas/CompanyResponse"
        destinationCompany:
          $ref: "#/components/schemas/CompanyResponse"
        originalExternalOrderId:
          type: string
          example: "ORD-998877"
        cost:
          type: number
          format: double
          example: 450.00
        requestDate:
          type: string
          format: date
          example: "2025-06-28"
        completionDate:
          type: string
          format: date
          nullable: true
          example: "2025-06-30"

    # Pickup Request Item Schemas
    PickupRequestItemRequest:
      type: object
      properties:
        itemDefinitionId:
          type: integer
          example: 1
        pickupRequestId:
          type: integer
          example: 1
        quantity:
          type: integer
          example: 50
      required:
        - itemDefinitionId
        - pickupRequestId
        - quantity
    PickupRequestItemResponse:
      type: object
      properties:
        pickupRequestItemId:
          type: integer
          readOnly: true
          example: 1
        itemDefinition:
          $ref: "#/components/schemas/ItemDefinitionResponse"
        pickupRequestId:
          type: integer
          example: 1
        quantity:
          type: integer
          example: 50

    # Bank Transactions Ledger Schemas
    BankTransactionsLedgerRequest:
      type: object
      properties:
        commercialBankTransactionId:
          type: string
          maxLength: 100
          nullable: true
          example: "cb-txn-abc-123"
        paymentReferenceId:
          type: string
          format: uuid
          nullable: true
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
        transactionCategoryId:
          type: integer
          example: 1
        amount:
          type: number
          format: double
          example: 450.00
        transactionDate:
          type: string
          format: date
          example: "2025-06-29"
        transactionStatusId:
          type: integer
          example: 1
        relatedPickupRequestId:
          type: integer
          nullable: true
          example: 1
        relatedLoanId:
          type: integer
          nullable: true
        relatedThohOrderId:
          type: string
          maxLength: 255
          nullable: true
      required:
        - transactionCategoryId
        - amount
        - transactionDate
        - transactionStatusId
    BankTransactionsLedgerResponse:
      type: object
      properties:
        transactionLedgerId:
          type: integer
          readOnly: true
          example: 1
        commercialBankTransactionId:
          type: string
          nullable: true
          example: "cb-txn-abc-123"
        paymentReferenceId:
          type: string
          format: uuid
          nullable: true
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
        transactionCategory:
          $ref: "#/components/schemas/TransactionCategoryResponse"
        amount:
          type: number
          format: double
          example: 450.00
        transactionDate:
          type: string
          format: date
          example: "2025-06-29"
        transactionStatusId:
          type: integer
          example: 1
        relatedPickupRequestId:
          type: integer
          nullable: true
          example: 1
        relatedLoanId:
          type: integer
          nullable: true
        relatedThohOrderId:
          type: string
          nullable: true

    # Transaction Category Schemas
    TransactionCategoryRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 50
          example: "Supplier Payment"
      required:
        - name
    TransactionCategoryResponse:
      type: object
      properties:
        transactionCategoryId:
          type: integer
          readOnly: true
          example: 1
        name:
          type: string
          example: "Supplier Payment"

    # Transaction Status Schemas
    TransactionStatusRequest:
      type: object
      properties:
        status:
          type: string
          maxLength: 50
          example: "Failed"
      required:
        - status
    TransactionStatusResponse:
      type: object
      properties:
        transactionStatusId:
          type: integer
          readOnly: true
          example: 1
        status:
          type: string
          example: "Failed"
