name: Prettier Auto Format

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  backend_code_formatting:
    name: Prettier backend auto format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Run Prettier and format code
        run: |
          cd backend
          npx prettier --write "**/*.{js,jsx,ts,tsx,css,md,json}"

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "chore: format backend code with Prettier"
            git push origin HEAD:${{ github.head_ref }}
          else
            echo "No formatting changes to commit."
          fi

  frontend_code_formatting:
    name: Prettier frontend auto format
    runs-on: ubuntu-latest
    needs: backend_code_formatting

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run Prettier and format code
        run: |
          cd frontend
          npx prettier --write "**/*.{js,jsx,ts,tsx,css,md,json}"

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "chore: format frontend code with Prettier"
            git push origin HEAD:${{ github.head_ref }}
          else
            echo "No formatting changes to commit."
          fi
